version: '3'

services:
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    container_name: db-api
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build:
      context: .
    container_name: youc-api
    ports:
      - "5000:5000"
    volumes:
      - ./application:/application
      - ./alembic:/alembic
    depends_on:
      - db
    env_file:
      .env
    networks:
      - default
    restart: always