"""Added video table

Revision ID: 404fd05c4feb
Revises: 4cb73252649e
Create Date: 2020-06-25 18:14:51.997010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404fd05c4feb'
down_revision = '4cb73252649e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('video_rate', sa.Integer(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_created_at'), 'video', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_created_at'), table_name='video')
    op.drop_table('video')
    # ### end Alembic commands ###
